//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolyTweetWPF.Service1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/PolyTweetWCF")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Service1.IServicePolyTweet")]
    public interface IServicePolyTweet {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePolyTweet/GetData", ReplyAction="http://tempuri.org/IServicePolyTweet/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePolyTweet/GetData", ReplyAction="http://tempuri.org/IServicePolyTweet/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePolyTweet/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IServicePolyTweet/GetDataUsingDataContractResponse")]
        PolyTweetWPF.Service1.CompositeType GetDataUsingDataContract(PolyTweetWPF.Service1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePolyTweet/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IServicePolyTweet/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<PolyTweetWPF.Service1.CompositeType> GetDataUsingDataContractAsync(PolyTweetWPF.Service1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePolyTweet/Connexion", ReplyAction="http://tempuri.org/IServicePolyTweet/ConnexionResponse")]
        bool Connexion(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePolyTweet/Connexion", ReplyAction="http://tempuri.org/IServicePolyTweet/ConnexionResponse")]
        System.Threading.Tasks.Task<bool> ConnexionAsync(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePolyTweet/ajouterUtilisateur", ReplyAction="http://tempuri.org/IServicePolyTweet/ajouterUtilisateurResponse")]
        bool ajouterUtilisateur(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePolyTweet/ajouterUtilisateur", ReplyAction="http://tempuri.org/IServicePolyTweet/ajouterUtilisateurResponse")]
        System.Threading.Tasks.Task<bool> ajouterUtilisateurAsync(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePolyTweet/supprimerUtilisateur", ReplyAction="http://tempuri.org/IServicePolyTweet/supprimerUtilisateurResponse")]
        bool supprimerUtilisateur(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePolyTweet/supprimerUtilisateur", ReplyAction="http://tempuri.org/IServicePolyTweet/supprimerUtilisateurResponse")]
        System.Threading.Tasks.Task<bool> supprimerUtilisateurAsync(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePolyTweet/findUtilisateur", ReplyAction="http://tempuri.org/IServicePolyTweet/findUtilisateurResponse")]
        bool findUtilisateur(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePolyTweet/findUtilisateur", ReplyAction="http://tempuri.org/IServicePolyTweet/findUtilisateurResponse")]
        System.Threading.Tasks.Task<bool> findUtilisateurAsync(string login);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicePolyTweetChannel : PolyTweetWPF.Service1.IServicePolyTweet, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicePolyTweetClient : System.ServiceModel.ClientBase<PolyTweetWPF.Service1.IServicePolyTweet>, PolyTweetWPF.Service1.IServicePolyTweet {
        
        public ServicePolyTweetClient() {
        }
        
        public ServicePolyTweetClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicePolyTweetClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicePolyTweetClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicePolyTweetClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public PolyTweetWPF.Service1.CompositeType GetDataUsingDataContract(PolyTweetWPF.Service1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<PolyTweetWPF.Service1.CompositeType> GetDataUsingDataContractAsync(PolyTweetWPF.Service1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public bool Connexion(string login, string password) {
            return base.Channel.Connexion(login, password);
        }
        
        public System.Threading.Tasks.Task<bool> ConnexionAsync(string login, string password) {
            return base.Channel.ConnexionAsync(login, password);
        }
        
        public bool ajouterUtilisateur(string login, string password) {
            return base.Channel.ajouterUtilisateur(login, password);
        }
        
        public System.Threading.Tasks.Task<bool> ajouterUtilisateurAsync(string login, string password) {
            return base.Channel.ajouterUtilisateurAsync(login, password);
        }
        
        public bool supprimerUtilisateur(string login, string password) {
            return base.Channel.supprimerUtilisateur(login, password);
        }
        
        public System.Threading.Tasks.Task<bool> supprimerUtilisateurAsync(string login, string password) {
            return base.Channel.supprimerUtilisateurAsync(login, password);
        }
        
        public bool findUtilisateur(string login) {
            return base.Channel.findUtilisateur(login);
        }
        
        public System.Threading.Tasks.Task<bool> findUtilisateurAsync(string login) {
            return base.Channel.findUtilisateurAsync(login);
        }
    }
}
